In [52]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF

from statistics import NormalDist
import itertools as it

In [53]:
f3_inputs = np.load("initial_inputs.npy")
f3_outputs = np.load("initial_outputs.npy")
f3_inputs_2 = np.load("initial_inputs2.npy")
f3_outputs_2 = np.load("initial_outputs2.npy")

In [54]:
f3_inputs = np.concatenate((f3_inputs, f3_inputs_2)) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.856453, 0.572658, 0.396564]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.419052, 0.525791, 0.668723]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.806453, 0.542658, 0.426564]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.95404 , 0.603434, 0.360707]])))
f3_inputs = np.concatenate((f3_inputs, np.array([[0.378686, 0.252828, 0.414646]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.872008, 0.592658, 0.394341]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.876453, 0.552658, 0.376564]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.836453, 0.579324, 0.385452]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.867564, 0.561546, 0.416564]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.852008, 0.563768, 0.409897]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.840896, 0.583768, 0.429897]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.756341, 0.548901, 0.444526]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.79493 , 0.426714, 0.384933]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.863119, 0.543768, 0.403231]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.845371, 0.518261, 0.394578]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.872008, 0.543768, 0.429897]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.85423 , 0.561545, 0.40323 ]]))) 
f3_inputs = np.concatenate((f3_inputs, np.array([[0.872008, 0.574879, 0.412119]]))) 

f3_outputs = np.concatenate((f3_outputs,f3_outputs_2)) 
f3_outputs = np.append(f3_outputs,-0.007556472239926157)
f3_outputs = np.append(f3_outputs,-0.11117041024766369)
f3_outputs = np.append(f3_outputs,-0.02486221525774178)
f3_outputs = np.append(f3_outputs,-0.02157038795559339)
f3_outputs = np.append(f3_outputs,-0.0503012651579929)
f3_outputs = np.append(f3_outputs,-0.01517794191050481)
f3_outputs = np.append(f3_outputs,-0.01595053598681603)
f3_outputs = np.append(f3_outputs,-0.010925064020108063)
f3_outputs = np.append(f3_outputs,-0.007386906470204272)
f3_outputs = np.append(f3_outputs,-0.004457685991172721)
f3_outputs = np.append(f3_outputs,-0.025865326752195786)
f3_outputs = np.append(f3_outputs,-0.011107628816793764)
f3_outputs = np.append(f3_outputs,-0.01562544524641375)
f3_outputs = np.append(f3_outputs,-0.010331415655822254)
f3_outputs = np.append(f3_outputs,-0.01698559042276884)
f3_outputs = np.append(f3_outputs,-0.017335638304868072)
f3_outputs = np.append(f3_outputs,-0.01188054501063807)
f3_outputs = np.append(f3_outputs,-0.008744864239247193)


In [55]:
f3_inputs

array([[0.17152521, 0.34391687, 0.2487372 ],
       [0.24211446, 0.64407427, 0.27243281],
       [0.53490572, 0.39850092, 0.17338873],
       [0.49258141, 0.61159319, 0.34017639],
       [0.13462167, 0.21991724, 0.45820622],
       [0.34552327, 0.94135983, 0.26936348],
       [0.15183663, 0.43999062, 0.99088187],
       [0.64550284, 0.39714294, 0.91977134],
       [0.74691195, 0.28419631, 0.22629985],
       [0.17047699, 0.6970324 , 0.14916943],
       [0.22054934, 0.29782524, 0.34355534],
       [0.66601366, 0.67198515, 0.2462953 ],
       [0.04680895, 0.23136024, 0.77061759],
       [0.60009728, 0.72513573, 0.06608864],
       [0.96599485, 0.86111969, 0.56682913],
       [0.16569979, 0.25685582, 0.65469   ],
       [0.65099632, 0.42417272, 0.52674437],
       [0.10601263, 0.24333177, 0.65025654],
       [0.35216426, 0.10580766, 0.06546785],
       [0.829086  , 0.4393692 , 0.20713429],
       [0.80489315, 0.31206954, 0.24371441],
       [0.46204056, 0.12939599, 0.83858636],
       [0.

In [56]:
f3_outputs

array([-0.1121222 , -0.08796286, -0.11141465, -0.03483531, -0.04800758,
       -0.11062091, -0.39892551, -0.11386851, -0.13146061, -0.09418956,
       -0.04694741, -0.10596504, -0.11804826, -0.03637783, -0.05675837,
       -0.12809391, -0.03103939, -0.1172756 , -0.07944403, -0.14258557,
       -0.11962132, -0.06119926, -0.03435924, -0.0876973 , -0.11502216,
       -0.07478879, -0.10441561, -0.08945485, -0.08760022, -0.02514614,
       -0.00755647, -0.11117041, -0.02486222, -0.02157039, -0.05030127,
       -0.01517794, -0.01595054, -0.01092506, -0.00738691, -0.00445769,
       -0.02586533, -0.01110763, -0.01562545, -0.01033142, -0.01698559,
       -0.01733564, -0.01188055, -0.00874486])

In [57]:
x_input = f3_inputs
y_input = f3_outputs

In [58]:
X_max= x_input[np.argmax((y_input))]
print(X_max)

[0.852008 0.563768 0.409897]


In [59]:
Y_max= y_input[np.argmax((y_input))]
print(Y_max)

-0.004457685991172721


In [60]:
x1 = np.linspace(0.852008-0.02, 0.852008+0.02, 10)
x2 = np.linspace(0.563768-0.02, 0.563768+0.02, 10)
x3 = np.linspace(0.409897-0.02, 0.409897+0.02, 10)

X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x3)):
            X_grid.append([x1[i], x2[j],x3[k]])
X_grid = np.array(X_grid)

#0.852008 0.563768 0.409897
#0.867564 0.561546 0.416564
#0.856453 0.572658 0.396564

In [61]:
noise_assumption = 1e-10
rbf_lengthscale =0.7
beta = 0.001
#beta = np.linspace(0.1, 0.9, 100)
#beta = np.linspace(1, 3, 100)
#beta = np.linspace(1, 50, 100)
variable_value = np.linspace(0.001, 0.09, 10)
result = []
for i in range(len(variable_value)):
    #beta = variable_value[i]
    kernel = RBF(length_scale=rbf_lengthscale, length_scale_bounds='fixed')
    model = GaussianProcessRegressor(kernel = kernel, alpha=noise_assumption)
    model.fit(np.array(x_input),np.array(y_input))
    post_mean, post_std = model.predict(np.array(X_grid), return_std=True)
    post_mean, post_std = post_mean.squeeze(), post_std.squeeze()
    acquisition_function = post_mean + beta* post_std
    result.append([variable_value[i],[X_grid[np.argmax(acquisition_function)]]])

In [62]:
result

[[0.001, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.010888888888888889, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.020777777777777777, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.030666666666666665, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.04055555555555555, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.050444444444444445, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.06033333333333333, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.07022222222222221, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.0801111111111111, [array([0.872008  , 0.57043467, 0.40323033])]],
 [0.09, [array([0.872008  , 0.57043467, 0.40323033])]]]