**Function 7:**

Sometimes Lazy is Best. You are now optimising six hyper-parameters of a machine learning model. Note that it is a popular and frequently used model, so maybe you could search to see if anyone else has optisized it before?

In [23]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF

from statistics import NormalDist
import itertools as it

In [24]:
f7_inputs = np.load("initial_inputs.npy")
f7_outputs = np.load("initial_outputs.npy")
f7_inputs_2 = np.load("initial_inputs2.npy")
f7_outputs_2 = np.load("initial_outputs2.npy")

In [25]:
f7_inputs = np.concatenate((f7_inputs, f7_inputs_2)) 
f7_inputs = np.concatenate((f7_inputs, np.array([[0.63626 , 0.749201, 0.1892  , 0.68919 , 0.593918, 0.199029]]))) 
f7_inputs = np.concatenate((f7_inputs, np.array([[0.368718, 0.581611, 0.450298, 0.514296, 0.368287, 0.298886]]))) 
f7_inputs = np.concatenate((f7_inputs, np.array([[0.060895, 0.501672, 0.251022, 0.221018, 0.450428, 0.750969]]))) 
f7_inputs = np.concatenate((f7_inputs, np.array([[0.531569, 0.712456, 0.129994, 0.411075, 0.641262, 0.863832]]))) 
f7_inputs = np.concatenate((f7_inputs, np.array([[0.055673, 0.489451, 0.245211, 0.215896, 0.413761, 0.440428]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.574342, 0.678895, 0.533896, 0.92418 , 0.554493, 0.523589]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.100001, 0.495555, 0.297777, 0.198888, 0.396666, 0.693333]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.088889, 0.493332, 0.282221, 0.205554, 0.403332, 0.695555]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.097778, 0.497777, 0.299999, 0.192221, 0.385554, 0.713333]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.699728, 0.60899 , 0.530807, 0.004961, 0.23617 , 0.606289]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.189374, 0.254933, 0.38873 , 0.226883, 0.365509, 0.859723]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.193819, 0.254933, 0.393174, 0.231327, 0.361065, 0.859723]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.039062, 0.040611, 0.422165, 0.057258, 0.711931, 0.146917]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.200485, 0.266044, 0.39984 , 0.237993, 0.354398, 0.848611]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.211596, 0.286044, 0.410951, 0.249104, 0.343286, 0.828611]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.222707, 0.306044, 0.422062, 0.260215, 0.332174, 0.808611]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.229373, 0.321599, 0.428728, 0.266881, 0.325507, 0.793055]])))
f7_inputs = np.concatenate((f7_inputs, np.array([[0.222706, 0.337154, 0.422061, 0.264658, 0.327729, 0.777499]])))

f7_outputs = np.concatenate((f7_outputs,f7_outputs_2)) 
f7_outputs = np.append(f7_outputs,0.6531409333073234)
f7_outputs = np.append(f7_outputs,0.8720881396978204)
f7_outputs = np.append(f7_outputs,1.159982626521815)
f7_outputs = np.append(f7_outputs,0.06394964228046124)
f7_outputs = np.append(f7_outputs,0.9892232332511364)
f7_outputs = np.append(f7_outputs,0.02270238658904679)
f7_outputs = np.append(f7_outputs,1.5980696671819323)
f7_outputs = np.append(f7_outputs,1.552462506402468)
f7_outputs = np.append(f7_outputs,1.5958875261823084)
f7_outputs = np.append(f7_outputs,0.31095147109238114)
f7_outputs = np.append(f7_outputs,2.1108344344203425)
f7_outputs = np.append(f7_outputs,2.141437825123243)
f7_outputs = np.append(f7_outputs,0.14128327861643816)
f7_outputs = np.append(f7_outputs,2.2404023030732505)
f7_outputs = np.append(f7_outputs,2.3917589697962973)
f7_outputs = np.append(f7_outputs,2.5103520273309883)
f7_outputs = np.append(f7_outputs,2.57198926677023)
f7_outputs = np.append(f7_outputs,2.5936857026275053)



In [26]:
X_max= f7_inputs[np.argmax((f7_outputs))]
print(X_max)

[0.222706 0.337154 0.422061 0.264658 0.327729 0.777499]


In [27]:
Y_max= f7_outputs[np.argmax((f7_outputs))]
print(Y_max)

2.5936857026275053


In [28]:
x1 = np.linspace(0.222706-0.02, 0.222706+0.02, 10)
x2 = np.linspace(0.337154-0.02, 0.337154+0.02, 10)
x3 = np.linspace(0.422061-0.02, 0.422061+0.02, 10)
x4 = np.linspace(0.264658-0.02, 0.264658+0.02, 10)
x5 = np.linspace(0.327729-0.02, 0.327729+0.02, 10)
x6 = np.linspace(0.777499-0.02, 0.777499+0.02, 10)
X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x3)):
            for l in range(len(x4)):
                for m in range(len(x5)):
                    for n in range(len(x6)):
                        X_grid.append([x1[i], x2[j],x3[k],x4[l],x5[m],x6[n]])
X_grid = np.array(X_grid)
#0.222706 0.337154 0.422061 0.264658 0.327729 0.777499
#0.229373 0.321599 0.428728 0.266881 0.325507 0.793055
#0.222707 0.306044 0.422062 0.260215 0.332174 0.808611
#0.211596 0.286044 0.410951 0.249104 0.343286 0.828611
#0.200485 0.266044 0.39984  0.237993 0.354398 0.848611
#0.193819 0.254933 0.393174 0.231327 0.361065 0.859723
#0.19159697 0.25271152 0.39095255 0.22910573 0.36328738 0.86194604
#0.19159697 0.25271152 0.39095255 0.22910573 0.36328738 0.86194604
#0.100001  , 0.495555  , 0.297777  , 0.198888  , 0.396666  , 0.693333 
#[0.05789554, 0.49167222, 0.24742222, 0.21811844, 0.42042833, 0.73096984]

In [29]:
f7_inputs

array([[0.27262382, 0.32449536, 0.89710881, 0.83295115, 0.15406269,
        0.79586362],
       [0.54300258, 0.9246939 , 0.34156746, 0.64648585, 0.71844033,
        0.34313266],
       [0.09083225, 0.66152938, 0.06593091, 0.25857701, 0.96345285,
        0.6402654 ],
       [0.11886697, 0.61505494, 0.90581639, 0.8553003 , 0.41363143,
        0.58523563],
       [0.63021764, 0.8380969 , 0.68001305, 0.73189509, 0.52673671,
        0.34842921],
       [0.76491917, 0.25588292, 0.60908422, 0.21807904, 0.32294277,
        0.09579366],
       [0.05789554, 0.49167222, 0.24742222, 0.21811844, 0.42042833,
        0.73096984],
       [0.19525188, 0.07922665, 0.55458046, 0.17056682, 0.01494418,
        0.10703171],
       [0.64230298, 0.83687455, 0.02179269, 0.10148801, 0.68307083,
        0.6924164 ],
       [0.78994255, 0.19554501, 0.57562333, 0.07365919, 0.25904917,
        0.05109986],
       [0.52849733, 0.45742436, 0.36009569, 0.36204551, 0.81689098,
        0.63747637],
       [0.72261522, 0

In [30]:
f7_outputs

array([6.04432696e-01, 5.62753067e-01, 7.50323668e-03, 6.14243025e-02,
       2.73046801e-01, 8.37465723e-02, 1.36496830e+00, 9.26449549e-02,
       1.78695987e-02, 3.35649360e-02, 7.35163042e-02, 2.06309698e-01,
       8.82563400e-03, 2.68400317e-01, 6.11525528e-01, 1.47981826e-02,
       2.74892508e-01, 6.67632469e-02, 4.21183545e-02, 2.70146502e-03,
       1.82090730e-02, 7.01602756e-03, 1.00506611e-01, 4.75395516e-01,
       6.75141631e-01, 5.16457219e-01, 3.77747962e-03, 3.13433331e-03,
       2.13425228e-02, 9.54111589e-02, 1.92262369e-02, 3.63302431e-01,
       5.54078747e-01, 5.03285693e-01, 3.78578840e-01, 3.51420597e-01,
       2.18384946e-02, 2.74181505e-03, 2.84503825e-03, 1.42061766e+00,
       4.00914794e-01, 7.63154709e-01, 5.41883328e-02, 1.48980895e+00,
       4.34444521e-01, 1.08014511e+00, 1.28917937e-01, 1.37702296e-01,
       1.83158802e-01, 4.76459379e-02, 3.76226779e-02, 1.27204165e-02,
       7.60433460e-02, 5.57235508e-02, 6.43550690e-02, 4.80363915e-02,
      

In [31]:
x_input = f7_inputs
y_input = f7_outputs

noise_assumption = 1e-10
rbf_lengthscale = 0.1
beta = 0.001

variable_value = np.linspace(0.001, 0.09, 10)
#variable_value = np.linspace(0.001, 0.09, 10)
#variable_value = np.linspace(0.1, 0.9, 100)
#variable_value = np.linspace(1, 3, 10)
#variable_value = np.linspace(1, 50, 100)
result = []
for i in range(len(variable_value)):
    #beta = variable_value[i]
    kernel = RBF(length_scale=rbf_lengthscale, length_scale_bounds='fixed')
    model = GaussianProcessRegressor(kernel = kernel, alpha=noise_assumption)
    model.fit(np.array(x_input),np.array(y_input))
    post_mean, post_std = model.predict(np.array(X_grid), return_std=True)
    post_mean, post_std = post_mean.squeeze(), post_std.squeeze()
    acquisition_function = post_mean + beta* post_std
    result.append([variable_value[i],[X_grid[np.argmax(acquisition_function)]]])

In [32]:
#[0.001,[array([0.06011776, 0.49389444, 0.24964444, 0.22034066, 0.41820611,0.44042833])]
#[0.001,[array([0.06011776, 0.49389444, 0.24964444, 0.22034066, 0.41820611,0.44042833])]
#[0.001,[array([0.05567332, 0.48945   , 0.2452    , 0.21589622, 0.41376166,0.44042833])]
#[0.001,[array([0.05567332, 0.48945   , 0.2452    , 0.21589622, 0.41376166,0.44042833])]
#[1.0, [array([0.080001, 0.515555, 0.277777, 0.218888, 0.416666, 0.673333])]],[1.2222222222222223,
#[0.001,[array([0.08888989, 0.49333278, 0.28222144, 0.20555467, 0.40333267, 0.69555522]

In [33]:
result

[[0.001,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.010888888888888889,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.020777777777777777,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.030666666666666665,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.04055555555555555,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.050444444444444445,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.06033333333333333,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.07022222222222221,
  [array([0.22937267, 0.33493178, 0.42872767, 0.26243578, 0.32995122,
          0.77972122])]],
 [0.0801111111111111,
  [array([0.22937267, 0.33493178, 0.