**Function 6:** 

Cake and Stuff. Time to get cooking! You are optimising a cake recipe. There are five ingredients. The outputs correspond to the sum of different objectives: flavor, consistency, calories, waste and cost. Each objective receives negative points by our expert taster. You want this sum to be as close to zero as possible!

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
#from statistics import mean, median, mode, stdev,NormalDist

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
#from scipy.stats import norm

from statistics import NormalDist
import itertools as it

In [4]:
f6_inputs = np.load("initial_inputs.npy")
f6_outputs = np.load("initial_outputs.npy")
f6_inputs_2 = np.load("initial_inputs2.npy")
f6_outputs_2 = np.load("initial_outputs2.npy")

In [5]:
f6_inputs = np.concatenate((f6_inputs, f6_inputs_2)) 
f6_inputs = np.concatenate((f6_inputs, np.array([[0.345535, 0.754647, 0.491966, 0.450836, 0.604032]]))) 
f6_inputs = np.concatenate((f6_inputs, np.array([[0.853367, 0.617629, 0.937563, 0.301578, 0.415393]]))) 
f6_inputs = np.concatenate((f6_inputs, np.array([[0.688186, 0.184692, 0.772551, 0.691116, 0.066401]]))) 
f6_inputs = np.concatenate((f6_inputs, np.array([[0.622911, 0.51695 , 0.236728, 0.47113 , 0.706154]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.668186, 0.204692, 0.792551, 0.711116, 0.086401]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.648186, 0.224692, 0.812551, 0.691116, 0.066401]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.648186, 0.184692, 0.812551, 0.731116, 0.106401]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.628186, 0.164692, 0.792551, 0.751116, 0.126401]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.668186, 0.204692, 0.832551, 0.751116, 0.126401]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.381006, 0.349024, 0.584465, 0.808867, 0.155764]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.427005, 0.337664, 0.600496, 0.733667, 0.176168]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.363984, 0.316227, 0.577013, 0.689438, 0.077835]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.459871, 0.365921, 0.606441, 0.783317, 0.239875]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.447005, 0.317664, 0.620496, 0.713667, 0.196168]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.435998, 0.406845, 0.668405, 0.811834, 0.130345]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.45466 , 0.346872, 0.657419, 0.858968, 0.11944]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.458766, 0.303592, 0.663674, 0.996131, 0.076816]])))
f6_inputs = np.concatenate((f6_inputs, np.array([[0.384916, 0.311188, 0.757855, 0.803686, 0.13494 ]])))

f6_outputs = np.concatenate((f6_outputs,f6_outputs_2)) 
f6_outputs = np.append(f6_outputs,-1.5810999457962531)
f6_outputs = np.append(f6_outputs,-1.8787437904480868)
f6_outputs = np.append(f6_outputs,-0.6247687161411921)
f6_outputs = np.append(f6_outputs,-1.718806647852857)
f6_outputs = np.append(f6_outputs,-0.5671773346921368)
f6_outputs = np.append(f6_outputs,-0.5874063902941494)
f6_outputs = np.append(f6_outputs,-0.5144914715079646)
f6_outputs = np.append(f6_outputs,-0.5415990286820394)
f6_outputs = np.append(f6_outputs,-0.5996653040294271)
f6_outputs = np.append(f6_outputs,-0.22072442707678375)
f6_outputs = np.append(f6_outputs,-0.18264958158407013)
f6_outputs = np.append(f6_outputs,-0.3440970432570667)
f6_outputs = np.append(f6_outputs,-0.23533067806486813)
f6_outputs = np.append(f6_outputs,-0.2639220819499121)
f6_outputs = np.append(f6_outputs,-0.17148052911247116)
f6_outputs = np.append(f6_outputs,-0.06247688853060665)
f6_outputs = np.append(f6_outputs,-0.4406374095498452)
f6_outputs = np.append(f6_outputs,-0.2633675699383991)


In [6]:
X_max= f6_inputs[np.argmax((f6_outputs))]
print(X_max)

[0.45466  0.346872 0.657419 0.858968 0.11944 ]


In [7]:
Y_max= f6_outputs[np.argmax((f6_outputs))]
print(Y_max)

-0.06247688853060665


In [8]:
x1 = np.linspace(0.427005-0.02, 0.427005+0.02, 10)
x2 = np.linspace(0.337664-0.02, 0.337664+0.02, 10)
x3 = np.linspace(0.600496-0.02, 0.600496+0.02, 10)
x4 = np.linspace(0.733667-0.02, 0.733667+0.02, 10)
x5 = np.linspace(0.176168-0.02, 0.176168+0.02, 10)
X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x3)):
            for l in range(len(x4)):
                for m in range(len(x5)):
                    X_grid.append([x1[i], x2[j],x3[k],x4[l],x5[m]])
X_grid = np.array(X_grid)
#0.427005 0.337664 0.600496 0.733667 0.176168
#0.381006 0.349024 0.584465 0.808867 0.155764
#[0.648186 0.184692 0.812551 0.731116 0.106401]
#[0.668186, 0.204692, 0.792551, 0.711116, 0.086401]
#[0.688186  , 0.184692  , 0.772551  , 0.691116  , 0.066401  ]

In [9]:
f6_inputs

array([[7.28186105e-01, 1.54692570e-01, 7.32551669e-01, 6.93996509e-01,
        5.64013105e-02],
       [2.42384347e-01, 8.44099972e-01, 5.77809099e-01, 6.79021284e-01,
        5.01952888e-01],
       [7.29522610e-01, 7.48106200e-01, 6.79774641e-01, 3.56552279e-01,
        6.71053683e-01],
       [7.70620242e-01, 1.14403744e-01, 4.67799319e-02, 6.48324285e-01,
        2.73549053e-01],
       [6.18812299e-01, 3.31802137e-01, 1.87287868e-01, 7.56238474e-01,
        3.28834798e-01],
       [7.84958094e-01, 9.10682349e-01, 7.08120104e-01, 9.59225429e-01,
        4.91149586e-03],
       [1.45110786e-01, 8.96684598e-01, 8.96322235e-01, 7.26271537e-01,
        2.36271991e-01],
       [9.45069068e-01, 2.88459051e-01, 9.78805764e-01, 9.61655587e-01,
        5.98015936e-01],
       [1.25720155e-01, 8.62724692e-01, 2.85443322e-02, 2.46605272e-01,
        7.51206241e-01],
       [7.57594355e-01, 3.55831415e-01, 1.65228997e-02, 4.34207205e-01,
        1.12433044e-01],
       [5.36796903e-01, 3.0878

In [10]:
f6_outputs

array([-0.71426495, -1.20995524, -1.67219994, -1.53605771, -0.82923655,
       -1.24704893, -1.23378638, -1.69434344, -2.57116963, -1.30911635,
       -1.14478485, -1.91267714, -1.62283895, -1.35668211, -2.0184254 ,
       -1.70255784, -1.29424696, -0.93575656, -2.15576776, -1.74688209,
       -1.51269542, -1.34959856, -1.82739562, -1.71602331, -0.97248425,
       -1.20521138, -1.10099104, -1.91309535, -1.05157417, -1.19458833,
       -2.06906505, -1.48937327, -1.82528398, -1.7476171 , -1.35823203,
       -1.44913772, -1.81134837, -2.00771782, -0.99967761, -1.67533648,
       -1.58109995, -1.87874379, -0.62476872, -1.71880665, -0.56717733,
       -0.58740639, -0.51449147, -0.54159903, -0.5996653 , -0.22072443,
       -0.18264958, -0.34409704, -0.23533068, -0.26392208, -0.17148053,
       -0.06247689, -0.44063741, -0.26336757])

In [11]:
x_input = f6_inputs
y_input = f6_outputs

In [12]:
noise_assumption = 1e-10
rbf_lengthscale = 0.1
beta = 0.001


variable_value = np.linspace(0.001, 0.09, 10)

#beta = np.linspace(0.001, 0.09, 10)
#beta = np.linspace(0.1, 0.9, 100)
#beta = np.linspace(1, 3, 100)
#beta = np.linspace(1, 50, 100)
result = []
for i in range(len(variable_value)):
    #beta = variable_value[i]
    kernel = RBF(length_scale=rbf_lengthscale, length_scale_bounds='fixed')
    model = GaussianProcessRegressor(kernel = kernel, alpha=noise_assumption)
    model.fit(np.array(x_input),np.array(y_input))
    post_mean, post_std = model.predict(np.array(X_grid), return_std=True)
    post_mean, post_std = post_mean.squeeze(), post_std.squeeze()
    acquisition_function = post_mean + beta* post_std
    result.append([variable_value[i],[X_grid[np.argmax(acquisition_function)]]])
    
    

In [13]:
#[0.001, [array([0.668186, 0.204692, 0.792551, 0.711116, 0.086401])]
#[0.001, [array([0.668186, 0.204692, 0.792551, 0.711116, 0.086401])]
#[0.001, [array([0.668186, 0.204692, 0.792551, 0.711116, 0.086401]
#[0.001, [array([0.668186, 0.204692, 0.792551, 0.711116, 0.086401])
#[0.001, [array([0.668186, 0.204692, 0.792551, 0.711116, 0.086401])]
#[0.001, [array([0.628186, 0.164692, 0.792551, 0.751116, 0.126401]
#1.0, [array([0.628186, 0.204692, 0.792551, 0.751116, 0.126401]

In [14]:
result

[[0.001, [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.010888888888888889,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.020777777777777777,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.030666666666666665,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.04055555555555555,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.050444444444444445,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.06033333333333333,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.07022222222222221,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.0801111111111111,
  [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]],
 [0.09, [array([0.447005, 0.357664, 0.580496, 0.753667, 0.156168])]]]