**Function 5:**

Yield in a Chemical Reaction. This time you are trying to optimise another four-dimensional black-box. It corresponds to the yield of a chemical process after processing in some factory. This type of process tends to be unimodal. Try to find the combination of chemicals that maximizes the yield!

In [31]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
#from statistics import mean, median, mode, stdev,NormalDist

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
#from scipy.stats import norm

from statistics import NormalDist
import itertools as it

In [32]:
f5_inputs = np.load("initial_inputs.npy")
f5_outputs = np.load("initial_outputs.npy")
f5_inputs_2 = np.load("initial_inputs2.npy")
f5_outputs_2 = np.load("initial_outputs2.npy")

In [33]:
f5_inputs = np.concatenate((f5_inputs, f5_inputs_2)) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.329622, 0.319559, 0.335951, 0.275429]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.630732, 0.255243, 0.163612, 0.663668]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.136884, 0.175429, 0.750162, 0.240518]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.156884, 0.185429, 0.730162, 0.834869]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.221966, 0.848702, 0.877261, 0.876293]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.2353  , 0.835369, 0.890595, 0.889626]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.255301, 0.815369, 0.910595, 0.909626]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.275301, 0.795369, 0.930595, 0.929626]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.295301, 0.775369, 0.950595, 0.949626]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.30362 , 0.92081 , 0.951794, 0.890271]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.30362 , 0.956366, 0.956239, 0.872493]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.288064, 0.967477, 0.954016, 0.856937]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.305842, 0.976366, 0.962905, 0.87027]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.290286, 0.996366, 0.982905, 0.890271]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.283619, 0.996366, 0.994016, 0.905826]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.285841, 0.987477, 0.994016, 0.925826]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.283618, 0.985544, 0.999999, 0.936937]]))) 
f5_inputs = np.concatenate((f5_inputs, np.array([[0.281395, 0.978877, 0.999999, 0.956937]]))) 

f5_outputs = np.concatenate((f5_outputs,f5_outputs_2))
f5_outputs = np.append(f5_outputs,131.1962333718706)
f5_outputs = np.append(f5_outputs,8.319139067926972)
f5_outputs = np.append(f5_outputs,15.916258413112816)
f5_outputs = np.append(f5_outputs,65.62143113848653)
f5_outputs = np.append(f5_outputs,1077.2793665718714)
f5_outputs = np.append(f5_outputs,1151.2287899694788)
f5_outputs = np.append(f5_outputs,1283.9813760530844)
f5_outputs = np.append(f5_outputs,1446.3325506169003)
f5_outputs = np.append(f5_outputs,1642.712076836066)
f5_outputs = np.append(f5_outputs,2043.5758440370957)
f5_outputs = np.append(f5_outputs,2246.9353067103452)
f5_outputs = np.append(f5_outputs,2221.1489548557843)
f5_outputs = np.append(f5_outputs,2475.0054048920615)
f5_outputs = np.append(f5_outputs,3030.1696296258147)
f5_outputs = np.append(f5_outputs,3286.085078568141)
f5_outputs = np.append(f5_outputs,3367.83461018011)
f5_outputs = np.append(f5_outputs,3526.9798701929503)
f5_outputs = np.append(f5_outputs,3659.8420356222346)


In [34]:
f5_inputs

array([[0.19144708, 0.03819337, 0.60741781, 0.41458414],
       [0.75865295, 0.53651774, 0.65600038, 0.36034155],
       [0.43834987, 0.8043397 , 0.21024527, 0.15129482],
       [0.70605083, 0.53419196, 0.26424335, 0.48208755],
       [0.83647799, 0.19360965, 0.6638927 , 0.78564888],
       [0.68343225, 0.11866264, 0.82904591, 0.56757661],
       [0.55362148, 0.66734998, 0.32380582, 0.81486975],
       [0.35235627, 0.32224153, 0.11697937, 0.47311252],
       [0.15378571, 0.72938169, 0.42259844, 0.44307417],
       [0.46344227, 0.63002451, 0.10790646, 0.9576439 ],
       [0.67749115, 0.35850951, 0.47959222, 0.07288048],
       [0.58397341, 0.14724265, 0.34809746, 0.42861465],
       [0.30688872, 0.31687813, 0.62263448, 0.09539906],
       [0.51114177, 0.817957  , 0.72871042, 0.11235362],
       [0.43893338, 0.77409176, 0.37816709, 0.93369621],
       [0.22418902, 0.84648049, 0.87948418, 0.87851568],
       [0.72526172, 0.47987049, 0.08894684, 0.75976022],
       [0.35548161, 0.63961937,

In [35]:
f5_outputs

array([6.44434399e+01, 1.83013796e+01, 1.12939795e-01, 4.21089813e+00,
       2.58370525e+02, 7.84343889e+01, 5.75715369e+01, 1.09571876e+02,
       8.84799176e+00, 2.33223610e+02, 2.44230883e+01, 6.44201468e+01,
       6.34767158e+01, 7.97291299e+01, 3.55806818e+02, 1.08885962e+03,
       2.88667516e+01, 4.51815703e+01, 4.31612757e+02, 9.97233189e+00,
       1.16473297e+03, 1.21188493e+02, 2.87522281e+02, 1.98066524e+03,
       5.28521436e+02, 6.59070325e+01, 2.73993040e+02, 3.34964253e+02,
       3.03509422e+00, 3.16811442e+02, 2.13695298e+03, 1.63923940e+01,
       1.47198474e+01, 7.44697895e+00, 5.40487146e+02, 1.52854400e+02,
       1.03383108e+02, 2.53166057e+02, 3.59261876e+01, 2.10925883e+00,
       1.31196233e+02, 8.31913907e+00, 1.59162584e+01, 6.56214311e+01,
       1.07727937e+03, 1.15122879e+03, 1.28398138e+03, 1.44633255e+03,
       1.64271208e+03, 2.04357584e+03, 2.24693531e+03, 2.22114895e+03,
       2.47500540e+03, 3.03016963e+03, 3.28608508e+03, 3.36783461e+03,
      

In [36]:
X_max= f5_inputs[np.argmax(abs(f5_outputs))]
print(X_max)

[0.281395 0.978877 0.999999 0.956937]


In [37]:
Y_max= f5_outputs[np.argmax(abs(f5_outputs))]
print(Y_max)

3659.8420356222346


In [38]:
x1 = np.linspace(0.281395-0.02, 0.281395+0.02, 10)
x2 = np.linspace(0.978877-0.02, 0.978877+0.00, 10)
x3 = np.linspace(0.999999-0.02, 0.999999+0.00, 10)
x4 = np.linspace(0.956937-0.02, 0.956937+0.02, 10)
X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x3)):
            for l in range(len(x4)):
                X_grid.append([x1[i], x2[j],x3[k],x4[l]])
X_grid = np.array(X_grid)
#0.281395 0.978877 0.999999 0.956937
#0.283618 0.985544 0.999999 0.936937
#0.285841 0.987477 0.994016 0.925826
#0.283619 0.996366 0.994016 0.905826
#0.290286 0.996366 0.982905 0.890271
#0.305842 0.976366 0.962905 0.87027 
#0.30362  0.956366 0.956239 0.872493
#0.30584223 0.93636618 0.95401692 0.88360492
#0.275301, 0.795369, 0.930595, 0.929626
#0.255301 0.815369 0.910595 0.909626
#0.2353   0.835369 0.890595 0.889626
#[ 0.22418902, 0.84648049, 0.87948418, 0.87851568]

In [39]:
x_input = f5_inputs
y_input = f5_outputs

In [40]:
real_noise_std = 1e-10 
noise_assumption = 1e-10

rbf_lengthscale = 0.1
variable_value = np.linspace(0.001, 0.09, 10)
#beta = np.linspace(0.1, 0.9, 100)
#beta = np.linspace(1, 3, 100)
#beta = np.linspace(1, 50, 100)
result = []
for i in range(len(variable_value)):
    beta = variable_value[i]
    kernel = RBF(length_scale=rbf_lengthscale, length_scale_bounds='fixed')
    model = GaussianProcessRegressor(kernel = kernel, alpha=noise_assumption)
    model.fit(np.array(x_input),np.array(y_input))
    post_mean, post_std = model.predict(np.array(X_grid), return_std=True)
    post_mean, post_std = post_mean.squeeze(), post_std.squeeze()
    acquisition_function = post_mean + beta* post_std
    result.append([variable_value[i],[X_grid[np.argmax(acquisition_function)]]])

In [41]:
#0.001, [array([0.30362001, 0.92081062, 0.9517947 , 0.89027159]


#[0.001, [array([0.2219668 , 0.84870271, 0.87726196, 0.87629346]
#[0.001, [array([0.2219668 , 0.84870271, 0.87726196, 0.87629346]
#[0.001, [array([0.2219668 , 0.84870271, 0.87726196, 0.87629346]
#[0.001, [array([0.2219668 , 0.84870271, 0.87726196, 0.87629346]
#[0.001, [array([0.2219668 , 0.84870271, 0.87726196, 0.87629346]
#[0.001, [array([0.2219668 , 0.84870271, 0.87726196, 0.87629346]

In [42]:
result

[[0.001, [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.010888888888888889,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.020777777777777777,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.030666666666666665,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.04055555555555555,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.050444444444444445,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.06033333333333333,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.07022222222222221,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.0801111111111111,
  [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]],
 [0.09, [array([0.26583944, 0.97443256, 0.999999  , 0.976937  ])]]]