**Function 8:** 

High-dimensional Optimisation. You’ve reach the final, 8-dimensional search space. High-dimensional black-box optimisation can be very difficult, so sticking to local solutions is not the worst idea here.
```

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
#from statistics import mean, median, mode, stdev,NormalDist

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
#from scipy.stats import norm

from statistics import NormalDist

In [16]:
f8_inputs = np.load("initial_inputs.npy")
f8_outputs = np.load("initial_outputs.npy")
f8_inputs_2 = np.load("initial_inputs2.npy")
f8_outputs_2 = np.load("initial_outputs2.npy")

In [17]:
f8_inputs = np.concatenate((f8_inputs, f8_inputs_2)) 

f8_inputs = np.concatenate((f8_inputs, np.array([[0.084259,0.384768,0.152956,0.83177,0.619797,0.838113,0.360231,0.819888]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.265797,0.781385,0.799061,0.737909,0.541671,0.059651,0.661726,0.249156]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.085447,0.080955,0.045928,0.041786,0.373935,0.831055,0.468307,0.923084]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.010576,0.090955,0.105928,0.061786,0.353935,0.891055,0.478307,0.943084]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.065447,0.080955,0.055928,0.051786,0.383935,0.841055,0.478307,0.913084]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.035447,0.080955,0.045928,0.041786,0.373935,0.831055,0.468307,0.923084]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.040447,0.080955,0.045928,0.041786,0.373935,0.831055,0.468307,0.923084]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.015447,0.080955,0.080928,0.041786,0.373935,0.866055,0.468307,0.923084]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.154598,0.138109,0.018722,0.059536,0.367817,0.883297,0.437297,0.865776]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.525834,0.680905,0.197024,0.703188,0.541326,0.930864,0.505922,0.13963]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.151301,0.185001,0.182801,0.197001,0.631301,0.538201,0.257201,0.594101]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.150301,0.194801,0.185401,0.194301,0.601801,0.534401,0.269901,0.604701]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.144501,0.190901,0.128601,0.104101,0.187601,0.654601,0.501901,0.841001]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.147401,0.209901,0.130901,0.128401,0.191901,0.630201,0.487101,0.802801]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.151301,0.085001,0.182801,0.197001,0.731301,0.538201,0.257201,0.394101]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.251301,0.185001,0.182801,0.297001,0.831301,0.538201,0.257201,0.494101]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.351301,0.285001,0.382801,0.397001,0.631301,0.538201,0.457201,0.494101]])))
f8_inputs = np.concatenate((f8_inputs, np.array([[0.251301,0.185001,0.182801,0.197001,0.731301,0.538201,0.357201,0.494101]])))

f8_outputs = np.concatenate((f8_outputs,f8_outputs_2)) 
f8_outputs = np.append(f8_outputs,9.2912571799561)
f8_outputs = np.append(f8_outputs,7.1918457066059)
f8_outputs = np.append(f8_outputs,9.6071159102679)
f8_outputs = np.append(f8_outputs,9.5519090503339)
f8_outputs = np.append(f8_outputs,9.5991537082679)
f8_outputs = np.append(f8_outputs,9.5992053102679)
f8_outputs = np.append(f8_outputs,9.6004463702679)
f8_outputs = np.append(f8_outputs,9.5828223402679)
f8_outputs = np.append(f8_outputs,9.5885735221739)
f8_outputs = np.append(f8_outputs,8.608506577299)
f8_outputs = np.append(f8_outputs,9.9607020326694)
f8_outputs = np.append(f8_outputs,9.9511627380494)
f8_outputs = np.append(f8_outputs,9.5927395277894)
f8_outputs = np.append(f8_outputs,9.6206379181294)
f8_outputs = np.append(f8_outputs,9.9653361726694)
f8_outputs = np.append(f8_outputs,9.9134032526694)
f8_outputs = np.append(f8_outputs,9.4536206526694)
f8_outputs = np.append(f8_outputs,9.8880531526694)


In [18]:
f8_inputs

array([[6.04994453e-01, 2.92215020e-01, 9.08452748e-01, 3.55506242e-01,
        2.01668719e-01, 5.75338005e-01, 3.10310951e-01, 7.34281377e-01],
       [1.78006959e-01, 5.66222654e-01, 9.94861845e-01, 2.10325006e-01,
        3.20152657e-01, 7.07908792e-01, 6.35384489e-01, 1.07131627e-01],
       [9.07697668e-03, 8.11626153e-01, 5.20520360e-01, 7.56866752e-02,
        2.65111825e-01, 9.16516894e-02, 5.92415145e-01, 3.67320262e-01],
       [5.06028164e-01, 6.53730123e-01, 3.63410779e-01, 1.77981049e-01,
        9.37283044e-02, 1.97425331e-01, 7.55826900e-01, 2.92472339e-01],
       [3.59909264e-01, 2.49075679e-01, 4.95997170e-01, 7.09214981e-01,
        1.14987195e-01, 2.89206921e-01, 5.57295151e-01, 5.93881726e-01],
       [7.78818344e-01, 3.41949948e-03, 3.37983130e-01, 5.19527778e-01,
        8.20906993e-01, 5.37246689e-01, 5.51347098e-01, 6.60032086e-01],
       [9.08649322e-01, 6.22496998e-02, 2.38259546e-01, 7.66603545e-01,
        1.32335962e-01, 9.90243814e-01, 6.88067822e-01, 7.

In [19]:
f8_outputs

array([7.3987211 , 7.00522736, 8.45948162, 8.28400781, 8.60611679,
       8.54174792, 7.32743458, 7.29987205, 7.95787474, 5.59219339,
       7.85454099, 6.79198578, 8.97655402, 7.3790829 , 9.598482  ,
       8.15998319, 7.13162397, 6.76796253, 7.43374407, 9.01307515,
       7.31089382, 5.84106731, 9.14163949, 8.81755844, 6.45194313,
       8.83074505, 9.34427428, 6.88784639, 8.04221254, 7.69236805,
       7.92375877, 8.42175924, 8.2780624 , 7.11345716, 6.40258841,
       8.47293632, 7.97768459, 7.46087219, 7.43659353, 9.18300525,
       7.38153659, 6.21406582, 8.34373778, 8.20235493, 7.0175736 ,
       8.15436185, 8.59988062, 7.41496438, 6.35307753, 7.04891614,
       8.83964993, 9.75508539, 9.069804  , 8.33091139, 9.08235861,
       9.06259425, 7.88211016, 6.8055637 , 9.22168616, 8.57638926,
       6.45101025, 8.95855365, 8.30868114, 9.23898119, 7.41316123,
       8.28986748, 8.14792352, 6.56627417, 8.64815107, 8.10407818,
       8.67513919, 8.73943795, 7.55172428, 8.25528511, 6.61336

In [20]:
X_max= f8_inputs[np.argmax(abs(f8_outputs))]
print(X_max)

[0.151301 0.085001 0.182801 0.197001 0.731301 0.538201 0.257201 0.394101]


In [21]:
Y_max= f8_outputs[np.argmax(abs(f8_outputs))]
print(Y_max)

9.9653361726694


In [22]:
x1 = np.linspace(0.151301-0.20, 0.151301+0.20, 5)
x2 = np.linspace(0.085001-0.20, 0.085001+0.20, 5)
x3 = np.linspace(0.182801-0.20, 0.182801+0.20, 5)
x4 = np.linspace(0.197001-0.20, 0.197001+0.20, 5)
x5 = np.linspace(0.731301-0.20, 0.731301+0.20, 5)
x6 = np.linspace(0.538201-0.20, 0.538201+0.20, 5)
x7 = np.linspace(0.257201-0.20, 0.257201+0.20, 5)
x8 = np.linspace(0.394101-0.20, 0.394101+0.20, 5)
X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x3)):
            for l in range(len(x4)):
                for m in range(len(x5)):
                    for n in range(len(x6)):
                        for o in range(len(x7)):
                            for p in range(len(x8)):
                                X_grid.append([x1[i], x2[j],x3[k],x4[l],x5[m],x6[n],x7[o],x8[p]])
X_grid = np.array(X_grid)
#0.151301 0.085001 0.182801 0.197001 0.731301 0.538201 0.257201 0.394101
#0.151301 0.185001 0.182801 0.197001 0.631301 0.538201 0.257201 0.594101
#0.04343225 0.10004702 0.22342261 0.01686426 0.28000728 0.36384718 0.32840638 0.83239639
#0.085447  , 0.080955  , 0.045928  , 0.041786  , 0.373935  ,0.831055  , 0.468307  , 0.923084
#from function8
#[0.05644741, 0.06595555, 0.02292868, 0.03878647, 0.40393544,0.80105533, 0.48830701, 0.89308498]

In [24]:
x_input = f8_inputs
y_input = f8_outputs
noise_assumption = 1e-10
rbf_lengthscale = 0.3
beta = 0.1
variable_value = np.linspace(0.001, 0.09, 10)
#beta = np.linspace(0.1, 0.9, 10)
#beta = np.linspace(1, 2, 10)
#beta = np.linspace(1, 50, 100)
result = []
for i in range(len(variable_value)):
    model = GaussianProcessRegressor(kernel = kernel, alpha=noise_assumption)
    #model.fit(np.array(X).reshape(-1, 1), np.array(Y).reshape(-1, 1))
    model.fit(np.array(x_input),np.array(y_input))
    post_mean, post_std = model.predict(np.array(X_grid), return_std=True)
    #post_mean, post_std = model.predict(np.array(x_input_test), return_std=True)
    post_mean, post_std = post_mean.squeeze(), post_std.squeeze()
    acquisition_function = post_mean + beta* post_std
    result.append([beta,[X_grid[np.argmax(acquisition_function)]]])
    #grid = x_grid.squeeze()
    #x = grid[np.argmax(acquisition_function)]
    

In [25]:
result

[[0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 [0.1,
  [array([0.151301, 0.185001, 0.182801, 0.297001, 0.731301, 0.538201,
          0.257201, 0.494101])]],
 

In [ ]:
#[0.151301, 0.085001, 0.182801, 0.197001, 0.731301, 0.538201,
          0.257201, 0.394101]